In [14]:
import mindspore as ms
import sqlite3
import numpy as np

In [9]:
conn = sqlite3.connect('ssq.db')
cur = conn.cursor()

In [13]:
data_sql = 'select id,red1,red2,red3,red4,red5,red6,blue from ssq'
cur.execute(data_sql)
data = cur.fetchall()
data

[(2016119, 9, 32, 30, 21, 19, 31, 4),
 (2016120, 6, 21, 28, 25, 2, 5, 9),
 (2016121, 28, 23, 2, 10, 25, 3, 9),
 (2016122, 15, 28, 23, 29, 22, 24, 8),
 (2016123, 9, 20, 12, 27, 14, 7, 16),
 (2016124, 32, 21, 9, 15, 27, 24, 10),
 (2016125, 1, 8, 6, 30, 20, 27, 3),
 (2016126, 12, 18, 6, 2, 19, 17, 10),
 (2016127, 17, 12, 7, 29, 31, 26, 16),
 (2016128, 11, 9, 27, 26, 4, 17, 13),
 (2016129, 33, 6, 8, 31, 5, 21, 14),
 (2016130, 23, 17, 27, 21, 3, 28, 1),
 (2016131, 19, 18, 25, 27, 10, 4, 2),
 (2016132, 28, 5, 8, 19, 27, 13, 7),
 (2016133, 15, 22, 21, 27, 33, 16, 15),
 (2016134, 33, 18, 13, 11, 12, 14, 13),
 (2016135, 33, 20, 2, 8, 18, 10, 12),
 (2016136, 10, 27, 2, 29, 20, 7, 3),
 (2016137, 32, 15, 10, 6, 1, 9, 14),
 (2016138, 7, 20, 24, 30, 25, 16, 7),
 (2016139, 28, 19, 26, 30, 6, 1, 3),
 (2016140, 32, 26, 2, 17, 1, 5, 10),
 (2016141, 24, 21, 4, 17, 13, 15, 15),
 (2016142, 21, 30, 10, 23, 1, 17, 12),
 (2016143, 9, 6, 24, 23, 25, 33, 13),
 (2016144, 27, 10, 4, 12, 33, 32, 5),
 (2016145, 1, 

In [ ]:
net = ms.nn.LSTM(7, 7, num_layers=1, has_bias=True, batch_first=False, dropout=0.0, bidirectional=False)

In [33]:
import mindspore as ms
import numpy as np
net = ms.nn.LSTM(10, 16, 2, has_bias=True, batch_first=True, bidirectional=False)
x = ms.Tensor(np.ones([3, 5, 10]).astype(np.float32))
h0 = ms.Tensor(np.ones([1 * 2, 3, 16]).astype(np.float32))
c0 = ms.Tensor(np.ones([1 * 2, 3, 16]).astype(np.float32))
output, (hn, cn) = net(x, (h0, c0))
print(x)
print(h0)
print(c0)
print(output)

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1

In [35]:
data

Tensor(shape=[1000, 7], dtype=Float32, value=
[[ 9.00000000e+00,  3.20000000e+01,  3.00000000e+01 ...  1.90000000e+01,  3.10000000e+01,  4.00000000e+00],
 [ 6.00000000e+00,  2.10000000e+01,  2.80000000e+01 ...  2.00000000e+00,  5.00000000e+00,  9.00000000e+00],
 [ 2.80000000e+01,  2.30000000e+01,  2.00000000e+00 ...  2.50000000e+01,  3.00000000e+00,  9.00000000e+00],
 ...
 [ 2.40000000e+01,  1.50000000e+01,  1.20000000e+01 ...  5.00000000e+00,  2.60000000e+01,  6.00000000e+00],
 [ 2.00000000e+00,  1.00000000e+01,  2.40000000e+01 ...  6.00000000e+00,  2.50000000e+01,  9.00000000e+00],
 [ 1.60000000e+01,  1.50000000e+01,  3.20000000e+01 ...  2.50000000e+01,  3.00000000e+00,  1.00000000e+01]])

In [36]:
x = ms.Tensor(np.array(data).astype(np.float32))
h0 = ms.Tensor(np.ones([1 * 2, 3, 16]).astype(np.float32))
c0 = ms.Tensor(np.ones([1 * 2, 3, 16]).astype(np.float32))
output, (hn, cn) = net(x, (h0, c0))
print(x)
print(h0)
print(c0)
print(output)

ValueError: Perm value can not exceed shape range, must be in [0, 1], but got perm:2

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore\core\ops\transpose.cc:108 mindspore::ops::TransposeInfer::InferShape
